[package]
name = "sample-project"
description = "A short description of my package"
version = "0.1.0"
edition = "2024"
authors = ["Bastian Asmussen <bastian@asmussen.tech>"]
readme = "README.md"
license-file = "LICENSE"

[dependencies]
